enum {
  //l_buddystore_first = 84000,
  l_buddystore_first = 1000000,
  l_buddystore_journal_queue_ops,
  l_buddystore_journal_queue_bytes,
  l_buddystore_journal_ops,
  l_buddystore_journal_bytes,
  l_buddystore_journal_latency,
  l_buddystore_journal_wr,
  l_buddystore_journal_wr_bytes,
  l_buddystore_data_wr_bytes,
  l_buddystore_data_wr_latency,
  l_buddystore_journal_all_latency,
  l_buddystore_journal_full,
  l_buddystore_committing,
  l_buddystore_commitcycle,
  l_buddystore_commitcycle_interval,
  l_buddystore_commitcycle_latency,
  l_buddystore_op_queue_max_ops,
  l_buddystore_op_queue_ops,
  l_buddystore_ops,
  l_buddystore_op_queue_max_bytes,
  l_buddystore_op_queue_bytes,
  l_buddystore_bytes,
  l_buddystore_apply_latency,
  l_buddystore_queue_transaction_latency_avg,
  l_buddystore_last,
};


